version: '3.8'

services:
  player-db:
    build:
      context: ./PlayerCardDB
      dockerfile: Dockerfile
    container_name: player-db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Thandi@0312!"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
      -  "1400:1433"
      
    volumes:
      - db_data:/var/opt/mssql
      - ./logs:/var/opt/mssql/log
    restart: always
    networks:
      - player-network
  mvc-app:
    build:
      context: .
      dockerfile: ./prjPlayerCardTrader/Dockerfile
    container_name: mvc-app
    environment:
      SQL_CONNECTION_STRING: "Server=player-db, 1433;Database=Player;Trusted_Connection=false;MultipleActiveResultSets=true;Encrypt=false;user id=sa;password=Thandi@0312!"
    ports:
      - "5001:80"
    depends_on:
      - player-db
    networks:
      - player-network

networks:
  player-network:
    driver: bridge

volumes:
  db_data:
